export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_ERROR = 'GET_COMMENTS_ERROR';

export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_ERROR = 'ADD_COMMENT_ERROR';

export const ASSIGN_CURRENT_COMMENT = 'ASSIGN_CURRENT_COMMENT';
export const ASSIGN_CURRENT_COMMENT_ERROR = 'ASSIGN_CURRENT_COMMENT_ERROR';
// export const RESET_CURRENT_COMMENT = 'RESET_CURRENT_COMMENT';
//
// export const UPDATE_COMMENT_SUCCESS = 'UPDATE_COMMENT_SUCCESS';
// export const UPDATE_COMMENT_ERROR = 'UPDATE_COMMENT_ERROR';

export const REMOVE_COMMENT_SUCCESS = 'REMOVE_COMMENT_SUCCESS';
export const REMOVE_COMMENT_ERROR = 'REMOVE_COMMENT_ERROR';

export const COMMENT_LOADING = 'COMMENT_LOADING';
export const RESET_COMMENT_STATE = 'RESET_COMMENT_STATE';
