export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_ERROR = 'GET_PRODUCT_ERROR';

export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR';

export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_ERROR = 'UPDATE_PRODUCT_ERROR';

export const VOTE_PRODUCT_SUCCESS = 'VOTE_PRODUCT_SUCCESS';
export const VOTE_PRODUCT_ERROR = 'VOTE_PRODUCT_ERROR';

export const UNVOTE_PRODUCT_SUCCESS = 'UNVOTE_PRODUCT_SUCCESS';
export const UNVOTE_PRODUCT_ERROR = 'UNVOTE_PRODUCT_ERROR';

export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';

export const PRODUCT_LOADING = 'PRODUCT_LOADING';
export const RESET_PRODUCT_STATE = 'RESET_PRODUCT_STATE';
